# Generated by Django 4.2.15 on 2024-08-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='store_name',
        ),
    ]
