# Generated by Django 4.2.15 on 2024-08-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_item',
        ),
    ]
