# Generated by Django 4.2.15 on 2024-08-21 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
