# Generated by Django 4.2.15 on 2024-08-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
